config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_for :users
  root "invoices#index"
  get '/view/:token', to: 'invoices#view', as: 'sharetoken'
  
  resources :invoices do
    resources :invoice_items
  end
  
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/invoice.rb
class Invoice < ApplicationRecord
    belongs_to :user
    has_many  :invoice_item, dependent: :destroy
    validates :name, presence: true
    validates :description, presence: true, length: { minimum: 5}
end

app/models/invoice_item.rb
class InvoiceItem < ApplicationRecord
  belongs_to :invoice
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :invoices
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/invoice_items_controller.rb
class InvoiceItemsController < ApplicationController

  def create
        @invoice = Invoice.find(params[:invoice_id])
        @invoice_item = @invoice.invoice_item.create(invoice_item_params)
        redirect_to invoice_path(@invoice)
    end

    def destroy
      @invoice = Invoice.find(params[:invoice_id])
      @invoice_item = @invoice.invoice_item.find(params[:id])
      @invoice_item.destroy
      redirect_to invoice_path(@invoice), status: :see_other
    end

    private
      def invoice_item_params
        params.require(:invoice_item).permit(:itemName)
      end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController

  def index
    @invoices = current_user.invoices.all
  end

  def show
    @invoice = current_user.invoices.find(params[:id])
  end

  def new
    @invoice = Invoice.new
  end

  def create
    @invoice = Invoice.new(invoice_params)
    @invoice.token = SecureRandom.uuid
    @invoice.user = current_user
    if @invoice.save
      redirect_to @invoice
    else
      render :new, status: :unprocessable_entity
    end
   end

 def edit
  @invoice = current_user.invoices.find(params[:id])
 end

 def update
  @invoice = current_user.invoices.find(params[:id])

  if @invoice.update(invoice_params)
    redirect_to @invoice
  else
    render :edit, status: :unprocessable_entity
  end
 end

 def view
  @invoice = Invoice.find_by(token: params[:token])
  render :show 
end

 def destroy
  @invoice = current_user.invoices.find(params[:id])
  @invoice.destroy

  redirect_to root_path, status: :see_other
 end


   private
    def invoice_params
      params.require(:invoice).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/invoice_items_helper.rb
module InvoiceItemsHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_form.html.erb
<%= form_with model: invoice do |form| %>
    <div>
      <%= form.label :name %><br>
      <%= form.text_field :name %>
      <% invoice.errors.full_messages_for(:name).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  
    <div>
      <%= form.label :description %><br>
      <%= form.text_area :description %><br>
      <% invoice.errors.full_messages_for(:description).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  
    <div>
      <%= form.submit %>
    </div>
  <% end %>
  

app/views/invoices/edit.html.erb
<h1>Edit Invoice</h1>

<%= render "form", invoice: @invoice %>

app/views/invoices/index.html.erb
<!-- invoices.html.erb -->

<style>
  h1 {
    font-size: 2em;
    text-align: center;
    margin-bottom: 1em;
  }

  ul {
    list-style-type: none;
    padding: 0;
    margin: 0;
  }

  li {
    margin-bottom: 0.5em;
  }

  a {
    color: #333;
    text-decoration: none;
    border-bottom: 2px solid #333;
  }

  a:hover {
    background-color: #333;
    color: #fff;
  }

  button {
    background-color: #333;
    color: #fff;
    padding: 0.5em 1em;
    border: none;
    border-radius: 0.5em;
    font-size: 1em;
    cursor: pointer;
  }

  button:hover {
    background-color: #444;
  }
</style>

<h1>Invoices</h1>

<ul>
  <% @invoices.each do |invoice| %>
    <li>
      <%= link_to invoice.name, invoice %>
    </li>
  <% end %>
</ul> 

<%= button_to "New Invoice", new_invoice_path, method: :get %>

app/views/invoices/new.html.erb
<h1>New Invoice</h1>



<%= form_with model: @invoice do |form| %>
    
    <%= render "form", invoice: @invoice %>
<% end %>

app/views/invoices/show.html.erb
<meta name="clipboard-write" content="true">

<h1><%= @invoice.name %></h1>

<p><%= @invoice.description %></p>

<h2>Invoice Items:</h2>
<% @invoice.invoice_item.each do |invoice_item| %>
  <p>
    <strong>itemName:</strong>
    <%= invoice_item.itemName %>
  </p>

  <p>
  <%= link_to "Destroy Item", [invoice_item.invoice, invoice_item],
      data: {
                turbo_method: :delete,
                turbo_confirm: "Are you sure?"
      } %>
  </p>
<% end %>

<h2>Add an item:</h2>
<%= form_with model: [ @invoice, @invoice.invoice_item.build ] do |form| %>
  <p>
    <%= form.label :itemName %><br>
    <%= form.text_field :itemName %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

<ul>
<li><%= link_to "Edit", edit_invoice_path(@invoice) %></li>
<br>
<li><%= link_to "Destroy", invoice_path(@invoice), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>

<h2>Share your invoice</h2>

<li><%= link_to "Share", sharetoken_path(@invoice.token), id: "share-link" %></li>

<script>
  // Get the share link element
  const shareLink = document.getElementById("share-link");

  // Add a click event listener to the share link
  shareLink.addEventListener("click", (event) => {

    // Prevent the default link behavior
    event.preventDefault();

    // Get the share URL
    const shareUrl = shareLink.href;

    // Copy the share URL to the clipboard
    const tempInput = document.createElement("input");
    tempInput.setAttribute("value", shareUrl);
    document.body.appendChild(tempInput);
    tempInput.select();
    document.execCommand("copy");
    document.body.removeChild(tempInput);

    // Copy the current URL to the clipboard
    const currentUrl = window.location.href;

    navigator.clipboard.writeText(currentUrl).then(() => {
      // Display a popup message
      alert("URL copied to clipboard");
     }).catch((error) => {
      console.error("Failed to copy: ", error);
    });

  });
  
</script>

app/views/itemname/_form.html.erb
<%= form_with model: [ @invoice, @invoice.items.build ] do |form| %>
    <p>
      <%= form.label :itemName %><br>
      <%= form.text_field :itemName %>
    </p>
    <p>
      <%= form.submit %>
    </p>
<% end %>
  

app/views/itemname/_itemname.html.erb
<p>
  <%= link_to "Destroy Item", [invoice_item.invoice, invoice_item],
      data: {
                turbo_method: :delete,
                turbo_confirm: "Are you sure?"
      } %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wallet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render 'shared/navbar' %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Invoices</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        
       <% if user_signed_in? %> 
         <li class="nav-item">
           <%= link_to "Sign out", destroy_user_session_path, data: { turbo_method: :delete }, class: 'nav-link' %>
         </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'Register', new_user_registration_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
            </li> 
        <% end %>
      </ul>
    </div>
</nav>